name: build and test

on:
  push:
  pull_request:
    branches: [ main ]
    paths:
      - '**.cs'
      - '**.csproj'

env:
  DOTNET_VERSION: '9.0.203'

jobs:
  build-and-test:

    name: build-and-test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Trust Dev Certs
        run: dotnet dev-certs https --trust

      - name: Test
        run: dotnet test --no-restore --verbosity normal --logger trx --results-directory "TestResults"

      - name: Upload dotnet test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: dotnet-results
          path: TestResults

      - name: Publish test results to GitHub UI
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: .NET Test Results
          path: TestResults/*.trx
          reporter: dotnet-trx

      - name: Build Docker image
        run: docker build -t summitapi:latest .